# Generated by Django 2.1b1 on 2018-07-12 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photos',
            name='photographer',
            field=models.CharField(default='Jayesh Singh', max_length=150),
        ),
    ]
