# Generated by Django 2.1b1 on 2018-07-12 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_photos_photographer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photographer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photographer_name', models.CharField(max_length=150)),
                ('city', models.CharField(max_length=50)),
                ('email_id', models.EmailField(max_length=254)),
                ('details', models.CharField(max_length=1000)),
            ],
        ),
        migrations.AlterField(
            model_name='photos',
            name='photographer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Photographer'),
        ),
    ]
